language: cpp
sudo: require
dist: trusty
compiler:
- clang
os:
- osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink cmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
before_script:
- cmake .
script:
- make leetcode_testcase -j4
- ./tests/testcase/leetcode_testcase
branches:
  only:
  - master
